/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./script.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#ff56ec",
        "error-container": "#9f0519",
        "surface-container-low": "#131319",
        "on-primary-container": "#005359",
        "primary-dim": "#00deec",
        "outline": "#76747b",
        "inverse-primary": "#006a71",
        "surface": "#0e0e13",
        "on-error-container": "#ffa8a3",
        "on-tertiary-fixed": "#294300",
        "on-tertiary": "#3d6100",
        "surface-tint": "#8ff5ff",
        "on-secondary-container": "#fff5f9",
        "primary-fixed-dim": "#00deec",
        "on-secondary-fixed": "#63005d",
        "on-surface-variant": "#acaab1",
        "surface-container-highest": "#25252d",
        "on-background": "#f9f5fd",
        "on-secondary": "#41003c",
        "primary-fixed": "#00eefc",
        "surface-container": "#19191f",
        "inverse-on-surface": "#55545b",
        "on-error": "#490006",
        "tertiary": "#bcff5f",
        "tertiary-container": "#a2f31f",
        "background": "#0e0e13",
        "primary": "#8ff5ff",
        "tertiary-fixed-dim": "#95e400",
        "surface-container-lowest": "#000000",
        "error-dim": "#d7383b",
        "surface-variant": "#25252d",
        "secondary-dim": "#ff56ec",
        "surface-bright": "#2c2b33",
        "secondary-fixed": "#ffbdee",
        "tertiary-fixed": "#a2f31f",
        "on-primary-fixed": "#003f43",
        "on-primary-fixed-variant": "#005e64",
        "on-tertiary-container": "#365700",
        "secondary-container": "#ab00a1",
        "on-tertiary-fixed-variant": "#3d6200",
        "error": "#ff716c",
        "on-primary": "#005d63",
        "inverse-surface": "#fcf8ff",
        "on-secondary-fixed-variant": "#94008b",
        "on-surface": "#f9f5fd",
        "surface-dim": "#0e0e13",
        "tertiary-dim": "#95e400",
        "outline-variant": "#48474d",
        "secondary-fixed-dim": "#ffa7ec",
        "surface-container-high": "#1f1f26",
        "primary-container": "#00eefc"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Manrope"],
        "label": ["Space Grotesk"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
