/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./script.js"],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "outline": "#76747b",
          "background": "#0e0e13",
          "on-secondary-fixed": "#530082",
          "on-secondary-container": "#fff5ff",
          "surface-container": "#19191f",
          "surface-dim": "#0e0e13",
          "outline-variant": "#48474d",
          "primary-fixed": "#00eefc",
          "surface": "#0e0e13",
          "on-secondary-fixed-variant": "#7c00c0",
          "on-error-container": "#ffa8a3",
          "secondary-container": "#9000de",
          "on-tertiary-fixed-variant": "#0d6200",
          "inverse-primary": "#006a71",
          "primary-dim": "#00deec",
          "on-surface-variant": "#acaab1",
          "on-error": "#490006",
          "error": "#ff716c",
          "on-primary": "#005d63",
          "secondary-fixed-dim": "#e1b2ff",
          "on-tertiary": "#0d6100",
          "on-primary-container": "#005359",
          "tertiary": "#8eff71",
          "on-primary-fixed-variant": "#005e64",
          "on-background": "#f9f5fd",
          "primary": "#8ff5ff",
          "primary-container": "#00eefc",
          "inverse-on-surface": "#55545b",
          "tertiary-container": "#2ff801",
          "on-surface": "#f9f5fd",
          "error-dim": "#d7383b",
          "on-primary-fixed": "#003f43",
          "tertiary-fixed": "#2ff801",
          "surface-variant": "#25252d",
          "surface-bright": "#2c2b33",
          "secondary-dim": "#aa30fa",
          "surface-container-low": "#131319",
          "inverse-surface": "#fcf8ff",
          "tertiary-fixed-dim": "#2be800",
          "on-tertiary-fixed": "#064200",
          "on-secondary": "#350056",
          "secondary": "#c97cff",
          "surface-container-highest": "#25252d",
          "surface-container-lowest": "#000000",
          "tertiary-dim": "#2be800",
          "on-tertiary-container": "#0b5800",
          "error-container": "#9f0519",
          "secondary-fixed": "#e9c4ff",
          "primary-fixed-dim": "#00deec",
          "surface-tint": "#8ff5ff",
          "surface-container-high": "#1f1f26"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "fontFamily": {
          "headline": ["Space Grotesk"],
          "body": ["Plus Jakarta Sans"],
          "label": ["Space Grotesk"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
